from audio_functions import *
from browser_functions import *
from default_va_functions import *


commands = {
    'найди': find,
    'google': find,
    'загугли': find, 
    'поищи': find, 
    'найти': find,
    "перевод": get_translation, 
    "перевести": get_translation, 
    "переведи": get_translation,
    "открой новую вкладку": add_new_tab, 
    "добавь новую вкладку": add_new_tab, 
    "новая вкладка": add_new_tab,
    "привет": play_greeting, 
    "здравствуй" : play_greeting,
    "добрый день": play_greeting,
    "здарова": play_greeting, 
    "приветик": play_greeting,
    "переключись на вкладку под номером": window_switch_to,
    "переключись на вкладку под номер": window_switch_to, 
    "переключись на вкладку потом номер": window_switch_to, 
    "переключись на вкладку с номером": window_switch_to,  
    "переключись на вкладку номер": window_switch_to, 
    "переключись на вкладку": window_switch_to,
    "перейди на вкладку под номером": window_switch_to,
    "перейди на вкладку под номер": window_switch_to, 
    "перейди на вкладку потом номер": window_switch_to, 
    "перейди на вкладку с номером": window_switch_to,  
    "перейди на вкладку номер": window_switch_to, 
    "перейди на вкладку": window_switch_to,
    "перезагрузи": refresh, 
    "перезагрузка": refresh, 
    "перезагрузи страницу": refresh, 
    "перезагрузка страницы": refresh,
    "заверши работу программы": finish_programm, 
    "заверши программу": finish_programm, 
    "заверши работу": finish_programm, 
    "закончить работу": finish_programm, 
    "завершил работу": finish_programm, 
    "выключи программу": finish_programm, 
    "завершить программу": finish_programm, 
    "завершить работу": finish_programm, 
    "останови программу": finish_programm,
    "который час": get_time, 
    "сколько времени": get_time, 
    'скажи время': get_time, 
    "сколько сейчас времени": get_time, 
    "время": get_time,
    "открой ссылку под номером": choose_link,
    "открой ссылку по номеру": choose_link,
    "открой ссылку под номер": choose_link, 
    "открой ссылку с номером": choose_link, 
    "открой ссылку номер": choose_link, 
    "перейди по ссылке под номером": choose_link,
    "перейди по ссылке по номеру": choose_link,
    "перейди по ссылке под номер": choose_link,
    "перейди по ссылке с номером": choose_link, 
    "перейди по ссылке номер": choose_link, 
    "выбери ссылку под номером": choose_link,
    "выбери ссылку по номеру": choose_link, 
    "выбери ссылку под номер": choose_link,
    "выбери ссылку с номером": choose_link, 
    "выбери ссылку номер": choose_link, 
    "перейди по ссылке": choose_link, 
    "нажми на ссылку под номером": choose_link,
    "нажми на ссылку по номеру": choose_link,
    "нажми на ссылку под номер": choose_link, 
    "нажми на ссылку с номером": choose_link, 
    "нажми на ссылку номер": choose_link, 
    "выбери ссылку": choose_link,
    "нажми на ссылку": choose_link,
    "установи новый максимум предложений": change_sentence_max,
    "измени максимум предложений": change_sentence_max,
    "новый максимум предложений": change_sentence_max,
    "установи новый максиму предложений": change_sentence_max,
    "измени максиму предложений": change_sentence_max,
    "новый максиму предложений": change_sentence_max,
    "установи новый максимум": change_sentence_max,
    "измени максимум": change_sentence_max,
    "новый максимум": change_sentence_max,
    "прочитай мне текст страницы": read_text,
    "зачитай мне текст страницы": read_text,
    "прочитай текст страницы": read_text,
    "зачитай текст страницы": read_text,
    "зачитай": read_text,
    "прочитай": read_text,
    "читай": read_text,
}